server:
  port: 8080
spring:
  boot:
    admin:
      client:
        url: http://127.0.0.1:8888
  application:
    name: springboot-admin-client
    
management:
    endpoints:
        web:
          exposure:
            include: "*"   