spring:
  datasource:
    primary:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url:  jdbc:mysql://192.168.2.147:3306/test1?characterEncoding=utf8
      username: root
      password: 123456
      
    secondary:  
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url:  jdbc:mysql://192.168.2.147:3306/test2?characterEncoding=utf8
      username: root
      password: 123456