spring:
  redis:
    database: 0
    host: 192.168.1.235
    port: 6379
    password: 
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
#    timeout: 0